---
# - name: Install common
#   hosts: localhost
#   become: yes
#   roles:
#     - common

# - name: Install kubernetes
#   hosts: localhost
#   become: yes
#   roles:
    # - kubernetes

# - name: Install aws
#   hosts: localhost
#   become: yes
#   roles:
#     - aws

- name: Fetch relevant github repos
  hosts: localhost
  become: no
  roles:
    - github
 
# - name: Install apps packages
#   hosts: localhost
#   become: yes
#   roles:
#     - apps