---
- name: Update cache and upgrade
  hosts: localhost
  become: yes
  roles:
    - update

- name: Install common
  hosts: localhost
  roles:
    - common

- name: Install docker
  hosts: localhost
  roles:
    - docker

- name: Install oh-my-zsh
  hosts: localhost
  roles:
    - oh-my-zsh

- name: Install kubernetes
  hosts: localhost
  roles:
    - kubernetes

- name: Install aws
  hosts: localhost
  become: yes
  roles:
    - aws

- name: Install go
  hosts: localhost
  become: yes
  roles:
    - golang

- name: Install python
  hosts: localhost
  become: yes
  roles:
    - python

- name: Setup dotfiles
  hosts: localhost
  become: no
  roles:
    - dotfiles

- name: Fetch relevant github repos
  hosts: localhost
  become: no
  roles:
    - github
 
- name: Install apps packages
  hosts: localhost
  become: yes
  roles:
    - apps