---
- name: Update cache and upgrade
  hosts: localhost
  become: yes
  roles:
    - update

- name: Install common
  hosts: localhost
  roles:
    - common

- name: Install kubernetes
  hosts: localhost
  become: yes
  roles:
    - kubernetes

- name: Install aws
  hosts: localhost
  become: yes
  roles:
    - aws

- name: Setup dotfiles
  hosts: localhost
  become: no
  roles:
    - dotfiles

- name: Fetch relevant github repos
  hosts: localhost
  become: no
  roles:
    - github
 
- name: Install apps packages
  hosts: localhost
  become: yes
  roles:
    - apps