---
- name: Create kube folder
  file:
    path: /home/wcarlsen/.kube
    state: directory

- name: Install kuberentes packages
  pacman:
    name:
      - kubectl
      - kubectx
      - k9s
      - minikube
    state: latest
    update_cache: yes

