---
- name: Create kube folder
  file:
    path: ~/.kube
    state: directory

- name: Install kuberentes packages
  pacman:
    name:
      - k9s
      - kubectl
      - kubectx
      - minikube
    state: latest
  become: yes
