---
- name: Install apps packages
  pacman:
    name:
      - alacritty
      - chromium
      - code
      - copyq
      - dbeaver
      - discord
      - flameshot
      - timeshift
      - transmission-gtk
      - virtualbox
      - vlc
    state: latest
  become: yes

- aur:
    use: yay
    name:
      - insomnia
      - slack-desktop
    state: latest
  become: no