---
- name: Install pacman packages
  pacman:
    name:
      - tmux
      - jq
      - neovim
      - thefuck
      - the_silver_searcher
      - zsh
      - git
      - hey
      - bat
      - tree
      - autojump
      - exa
    state: latest
    update_cache: yes

