---
- name: Install pacman packages
  pacman:
    name:
      - bat
      - base-devel
      - docker
      - exa
      - git
      - hey
      - jq
      - neovim
      - the_silver_searcher
      - thefuck
      - tmux
      - tree
      - yay
      - zsh
    state: latest
  become: yes

- aur:
    use: yay
    name:
      - autojump-git
    state: latest
  become: no

- name: Check if oh-my-zsh is installed
  stat:
    path: ~/.oh-my-zsh
  register: omz

- name: Install oh-my-zsh
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  when: omz.stat.exists == False
