---
- name: Install pacman packages
  pacman:
    name:
      - bat
      - base-devel
      - exa
      - git
      - github-cli
      - hey
      - jq
      - neovim
      - the_silver_searcher
      - thefuck
      - tmux
      - tree
      - yay
    state: latest
  become: yes

- aur:
    use: yay
    name:
      - autojump-git
    state: latest
  become: no
